### ISSUE TITLE
Container does not work?

### ISSUE THREAD

**Issue by Alradas** [mybb/docker#3]
I installed a docker container just a few seconds ago with following exact command:

docker container run -d --name mybb-test -p 8099:80/tcp mybb/mybb:latest
![image](https://user-images.githubusercontent.com/29652545/86914638-ef87f380-c120-11ea-9289-88feee85c8c1.png)

I wanted to open the container called "mybb-test" on the port 8099 of my host-system (80 is already in use).
I understand that there is no database or anything yet, but normally after installing mybb you get this nice install wizard and when I try to open my ip plus the port in the browser I only get a denied request message.

![image](https://user-images.githubusercontent.com/29652545/86914577-d7b06f80-c120-11ea-8c92-b46afbbf6bf2.png)

What am I doing wrong?

**Comment by kawaii** [comment]
The MyBB container only contains the PHP-FPM service + the MyBB files, you need to also create an nginx container with the appropriate configuration mounted in order to reverse proxy to the MyBB container.

https://github.com/mybb/docker#-via-docker-stack-deploy-or-docker-compose
https://gist.github.com/kawaii/ed2fbbf11309b8f635a623fa87abce8d
